export const routes = {
	home: '/',
	login: '/login',
	signUp: '/sign_up',
	vocalTraining: '/vocal_training',
	danceTraining: '/dance_training',
	recruit: '/recruit',
	freeBoard: '/free_board',
	teamRecruit: '/team_recruit',
	portfolio: '/portfolio',
	portfolioIntro: '/portfolio/intro',
	portfolioVocal: '/portfolio/vocal',
	portfolioDance: '/portfolio/dance',
	portfolioRap: '/portfolio/rap',
	portfolioImage: '/portfolio/image',
};