export const routes = {
	home: '/',
	login: '/login',
	signUp: '/sign_up',
	trainingRoom: '/training_room',
	recruit: '/recruit',
	community: '/community',
	portfolio: '/portfolio',
	portfolioIntro: '/portfolio/intro',
	portfolioVocal: '/portfolio/vocal',
	portfolioDance: '/portfolio/dance',
	portfolioRap: '/portfolio/rap',
	portfolioImage: '/portfolio/image',
	mypage: '/mypage',
	modifyInfo: '/modifyinfo',
	selectedInfo: '/selectedinfo',
};